# Generated by Django 4.0.4 on 2022-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255, verbose_name='Website Link')),
            ],
        ),
    ]
