# Generated by Django 4.0.4 on 2022-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrmeyer', '0003_group_productliters_productpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
